max-gamma = 120

profile {
    time = 07:00
    identity = true
    gamma = 1.0
}

profile {
    time = 19:30
    temperature = 5000
    gamma = 0.95
}

profile {
    time = 22:00
    temperature = 4200
    gamma = 0.85
}
